name: Deploy React App to Staging Server
on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code.
        uses: actions/checkout@master

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install Dependencies
        run: cd client && npm install

      - name: Build
        run: cd client && CI='false' npm run build
        env:
          REACT_APP_API_BASE_URL: ${{vars.STAGING_API_URL}}

      - name: Test
        run: echo ${{vars.STAGING_API_URL}}}

      - name: S3 Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        run: |
          aws s3 cp --recursive --region ap-northeast-2 client/build s3://${{ secrets.BUCKET_NAME }}

      - name: CloudFront Invalidation
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: ap-northeast-2
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{secrets.DISTRIBUTION_ID}} \
            --paths "/*"
